# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(verbose_name='ID автора')),
                ('header', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[500, 500], upload_to='', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.TextField(choices=[('Категория 1', 'Категория 1'), ('Категория 2', 'Категория 2'), ('Категория 3', 'Категория 3'), ('Категория 4', 'Категория 4')], default='Не выбрано', max_length=100, verbose_name='Категория')),
                ('city', models.CharField(choices=[('Омск', 'Омск'), ('Тара', 'Тара'), ('Тюмень', 'Тюмень'), ('Новосибирск', 'Новосибирск')], default='Не выбрано', max_length=20, verbose_name='Город')),
                ('public_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Активное объявление')),
                ('moderated', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[360, 360], upload_to='', verbose_name='Аватар')),
                ('city', models.CharField(choices=[('Омск', 'Омск'), ('Тара', 'Тара'), ('Тюмень', 'Тюмень'), ('Новосибирск', 'Новосибирск')], default='Не выбрано', max_length=20, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
