# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=123, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('Категория 1', 'Категория 1'), ('Категория 2', 'Категория 2'), ('Категория 3', 'Категория 3'), ('Категория 4', 'Категория 4')], default='Не выбрано', max_length=100, verbose_name='Категория'),
        ),
    ]
