# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_auto_20171105_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='qwer@mail.ru', max_length=100, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
