# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0005_auto_20171107_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
    ]
