# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0007_сategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategory',
            new_name='Category',
        ),
    ]
