# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0009_auto_20171109_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[500, 500], upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='boxes_count',
            field=models.IntegerField(verbose_name='Количество карточек/купонов'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='objects_in_box',
            field=models.IntegerField(verbose_name='Колиество бонусов'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shop',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='Board.Shop', verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
