# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0010_auto_20171111_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.City', verbose_name='Город'),
        ),
    ]
