# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:32
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0011_auto_20171111_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], keep_meta=True, quality=0, size=[473, 297], upload_to='', verbose_name='Фото'),
        ),
    ]
