# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:46
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0012_auto_20171113_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], keep_meta=True, quality=0, size=[473, 297], upload_to='', verbose_name='Фото'),
        ),
    ]
