# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0014_auto_20171123_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='other_city',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Другой город'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='other_shop',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Другой магазин'),
        ),
    ]
