# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0015_auto_20171123_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='other_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Другой город'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='other_shop',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Другой магазин'),
        ),
    ]
