# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0016_auto_20171123_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='units',
            field=models.CharField(default='штуки', max_length=15, verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], keep_meta=True, quality=0, size=[473, 297], upload_to='', verbose_name='Фото'),
        ),
    ]
