# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='header',
            field=models.CharField(default='123', max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Скриншот'),
        ),
    ]
