# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0020_auto_20171130_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=13, verbose_name='Имя'),
        ),
    ]
