# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0021_auto_20171201_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='active',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
