# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0022_auto_20171202_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
