# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0025_profile_currentip'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='other_category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Другая категория'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentIP',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Текущий IP входа'),
        ),
    ]
