# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0026_auto_20171203_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='objects_in_box',
            field=models.IntegerField(verbose_name='Количество бонусов'),
        ),
    ]
