# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0027_auto_20171204_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='public_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
