# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0029_auto_20171205_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='public_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
